import type { APIRoute } from 'astro';
import { getPageEntries } from '../utils/content-extractor.js';

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

export const GET: APIRoute = async ({ site }) => {
  const baseUrl = site?.toString().replace(/\/$/, '') ?? '';
  const entries = await getPageEntries(baseUrl, options.exclude ?? [], options.collections);

  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;
  const siteDescription = options.siteDescription ?? '';

  const lines: string[] = [];

  // Header
  lines.push(`# ${siteName}`);
  if (siteDescription) {
    lines.push(`> ${siteDescription}`);
  }
  lines.push('');

  // Group entries by collection
  const groups = new Map<string, typeof entries>();
  for (const entry of entries) {
    const group = entry.collection ?? 'pages';
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)!.push(entry);
  }

  for (const [group, items] of groups) {
    const heading = group.charAt(0).toUpperCase() + group.slice(1);
    lines.push(`## ${heading}`);
    lines.push('');
    for (const item of items) {
      const desc = item.description ? ` - ${item.description}` : '';
      lines.push(`- [${item.title}](${baseUrl}${item.url})${desc}`);
    }
    lines.push('');
  }

  // Machine-readable versions note
  lines.push('## Machine-readable pages');
  lines.push('');
  lines.push(
    'Each page on this site has a plain-text version at `[page-url]/machine.txt`.'
  );
  lines.push(
    'Example: `' + baseUrl + '/about/machine.txt`'
  );
  lines.push('');
  if (options.attribution !== false) {
    lines.push('---');
    lines.push('Generated by astro-inference');
  }

  return new Response(lines.join('\n'), {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
