import type { APIRoute } from 'astro';
import { htmlToMarkdown } from '../utils/markdown-renderer.js';
import { isExcluded } from '../utils/url-utils.js';

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

// Must be on-demand (not pre-rendered) — the slug is unknown at build time
export const prerender = false;

const FETCH_TIMEOUT_MS = 10_000;

export const GET: APIRoute = async ({ params, site, request }) => {
  const slug = params.inferenceSlug ?? '';
  const origin = new URL(request.url).origin;
  const baseUrl = site?.toString().replace(/\/$/, '') ?? origin;

  // Reconstruct the original page URL using the request origin (works in dev + prod)
  // Append trailing slash — Astro's trailingSlash:'always' serves pages at slug/
  const pagePath = slug ? `/${slug}/` : '/';
  const pageUrl = `${origin}${pagePath}`;

  // Check if this path is excluded (use path without trailing slash for comparison)
  const exclude: string[] = options.exclude ?? [];
  const excludePath = slug ? `/${slug}` : '/';
  if (isExcluded(excludePath, exclude)) {
    return new Response('Not found', { status: 404 });
  }

  // Fetch the actual page HTML from the running Astro server.
  // Keep the AbortController alive through both fetch AND body read so the
  // full 10s timeout covers the entire operation (not just the connection).
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

  let pageHtml: string;
  try {
    const res = await fetch(pageUrl, {
      signal: controller.signal,
      headers: {
        'X-Astro-Inference': '1',
        Accept: 'text/html',
      },
    });

    if (!res.ok) {
      return new Response('Page not found', { status: 404 });
    }

    pageHtml = await res.text();
  } catch (err) {
    if (controller.signal.aborted) {
      return new Response('Request timed out', { status: 504 });
    }
    return new Response('Could not fetch page', { status: 502 });
  } finally {
    clearTimeout(timeoutId);
  }

  const markdown = htmlToMarkdown(pageHtml);

  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;

  const header = [
    `# ${siteName}`,
    `> Source: ${pageUrl}`,
    `> Machine-readable version - ${new Date().toISOString().split('T')[0]}`,
    '',
    '---',
    '',
  ].join('\n');

  const footer = options.attribution !== false
    ? ['\n---', `Generated by astro-inference | ${baseUrl}/llms.txt`].join('\n')
    : '';

  return new Response(header + markdown + footer, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};
