import type { APIRoute } from 'astro';
import { htmlToMarkdown } from '../utils/markdown-renderer.js';

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

// Must be on-demand (not pre-rendered) — the slug is unknown at build time
export const prerender = false;

export const GET: APIRoute = async ({ params, site, request }) => {
  console.log('[astro-inference] machine.txt hit, params:', params, 'url:', request.url);
  const slug = params.inferenceSlug ?? '';
  const origin = new URL(request.url).origin;
  const baseUrl = site?.toString().replace(/\/$/, '') ?? origin;

  // Reconstruct the original page URL using the request origin (works in dev + prod)
  // Append trailing slash — Astro's trailingSlash:'always' serves pages at slug/
  const pagePath = slug ? `/${slug}/` : '/';
  const pageUrl = `${origin}${pagePath}`;

  // Check if this path is excluded (use path without trailing slash for comparison)
  const exclude: string[] = options.exclude ?? [];
  const excludePath = slug ? `/${slug}` : '/';
  if (isExcluded(excludePath, exclude)) {
    return new Response('Not found', { status: 404 });
  }

  // Fetch the actual page HTML from the running Astro server
  let pageHtml: string;
  try {
    const res = await fetch(pageUrl, {
      headers: {
        // Signal to the Astro app that this is an internal machine request
        'X-Astro-Inference': '1',
        Accept: 'text/html',
      },
    });

    if (!res.ok) {
      return new Response(`Page not found: ${pageUrl}`, { status: 404 });
    }

    pageHtml = await res.text();
  } catch {
    return new Response(`Could not fetch page: ${pageUrl}`, { status: 502 });
  }

  const markdown = htmlToMarkdown(pageHtml);

  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;
  const machineSuffix = options.machineSuffix ?? 'machine.txt';

  const header = [
    `# ${siteName}`,
    `> Source: ${pageUrl}`,
    `> Machine-readable version - ${new Date().toISOString().split('T')[0]}`,
    '',
    '---',
    '',
  ].join('\n');

  const footer = options.attribution !== false
    ? ['\n---', `Generated by astro-inference | ${baseUrl}/llms.txt`].join('\n')
    : '';

  return new Response(header + markdown + footer, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};

function isExcluded(url: string, patterns: string[]): boolean {
  return patterns.some((pattern) => {
    if (pattern.endsWith('/*')) return url.startsWith(pattern.slice(0, -2));
    return url === pattern;
  });
}
