import { describe, it, expect } from 'vitest';
import { buildLlmsFullTxt } from './llms-full.js';

describe('buildLlmsFullTxt', () => {
  it('includes the site name heading and each page section', () => {
    const out = buildLlmsFullTxt(
      'My Site',
      [
        { url: 'https://example.com/', markdown: 'Home content' },
        { url: 'https://example.com/about', markdown: 'About content' },
      ],
      ''
    );

    expect(out).toContain('# My Site');
    expect(out).toContain('## https://example.com/');
    expect(out).toContain('Home content');
    expect(out).toContain('## https://example.com/about');
    expect(out).toContain('About content');
  });

  it('separates sections with a horizontal rule', () => {
    const out = buildLlmsFullTxt(
      'My Site',
      [
        { url: '/a', markdown: 'A' },
        { url: '/b', markdown: 'B' },
      ],
      ''
    );

    expect(out.split('\n\n---\n\n').length).toBe(3);
  });

  it('appends the footer when provided', () => {
    const out = buildLlmsFullTxt('My Site', [{ url: '/', markdown: 'Home' }], 'Generated by astro-inference');

    expect(out.endsWith('Generated by astro-inference')).toBe(true);
    expect(out).toContain('\n\n---\n');
  });

  it('omits the trailing footer separator when footer is empty', () => {
    const out = buildLlmsFullTxt('My Site', [{ url: '/', markdown: 'Home' }], '');

    expect(out.endsWith('Home')).toBe(true);
  });

  it('handles an empty page list', () => {
    const out = buildLlmsFullTxt('My Site', [], '');
    expect(out).toBe('# My Site\n> Full-text content of every page on this site - ' + new Date().toISOString().split('T')[0]);
  });
});
