import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import type { AstroIntegration } from 'astro';
import type { AstroInferenceOptions } from './types.js';
import { htmlToMarkdown } from './utils/markdown-renderer.js';

export type { AstroInferenceOptions, PageEntry } from './types.js';

export default function astroInference(
  options: AstroInferenceOptions = {}
): AstroIntegration {
  const {
    llmsTxtPath = '/llms.txt',
    machineSuffix = 'machine.txt',
  } = options;

  let siteUrl = '';

  return {
    name: 'astro-inference',
    hooks: {
      'astro:config:setup': ({ injectRoute, addMiddleware, updateConfig, config }) => {
        siteUrl = config.site?.toString().replace(/\/$/, '') ?? '';

        // Pass options to routes via Astro virtual module config
        updateConfig({
          vite: {
            plugins: [viteInferenceOptions(options)],
          },
        });

        // Absolute paths so Astro resolves them regardless of install method
        const llmsEntrypoint = fileURLToPath(new URL('./routes/llms.txt.js', import.meta.url));
        const middlewareEntrypoint = fileURLToPath(new URL('./middleware.js', import.meta.url));

        // /llms.txt — static route, works in both dev and build
        injectRoute({
          pattern: llmsTxtPath,
          entrypoint: llmsEntrypoint,
        });

        // Dev mode: middleware intercepts */machine.txt requests on-the-fly
        addMiddleware({
          entrypoint: middlewareEntrypoint,
          order: 'pre',
        });
      },

      // Build mode: generate a static machine.txt for every HTML page
      'astro:build:done': async ({ dir, pages, logger }) => {
        const exclude = options.exclude ?? [];
        const siteName = options.siteName ?? new URL(siteUrl || 'http://localhost').hostname;
        const today = new Date().toISOString().split('T')[0];

        let count = 0;

        for (const { pathname } of pages) {
          if (isExcluded(pathname, exclude)) continue;

          // pathname is like '/about-me/' or '/' — map to dist/about-me/index.html
          const segment = pathname.replace(/^\/|\/$/g, '');
          const htmlPath = fileURLToPath(
            new URL(segment ? `${segment}/index.html` : 'index.html', dir)
          );

          let html: string;
          try {
            html = await readFile(htmlPath, 'utf-8');
          } catch {
            // Astro can also emit segment.html (no trailing slash / directory index)
            const flatHtmlPath = fileURLToPath(
              new URL(segment ? `${segment}.html` : 'index.html', dir)
            );
            try {
              html = await readFile(flatHtmlPath, 'utf-8');
            } catch {
              continue; // not an HTML page (rss, sitemap, etc.)
            }
          }

          const markdown = htmlToMarkdown(html);
          const sourceUrl = `${siteUrl}/${pathname}`;

          const header = [
            `# ${siteName}`,
            `> Source: ${sourceUrl}`,
            `> Machine-readable version - ${today}`,
            '',
            '---',
            '',
          ].join('\n');

          const footer = options.attribution !== false
            ? `\n---\nGenerated by astro-inference | ${siteUrl}/llms.txt`
            : '';

          const outPath = fileURLToPath(
            new URL(segment ? `${segment}/${machineSuffix}` : machineSuffix, dir)
          );

          await writeFile(outPath, header + markdown + footer, 'utf-8');
          count++;
        }

        logger.info(`Generated ${count} ${machineSuffix} files`);
      },
    },
  };
}

function isExcluded(url: string, patterns: string[]): boolean {
  return patterns.some((pattern) => {
    if (pattern.endsWith('/*')) return url.startsWith(pattern.slice(0, -2));
    return url === pattern;
  });
}

/** Vite virtual module so routes can read options without importing Node APIs */
function viteInferenceOptions(options: AstroInferenceOptions) {
  const virtualModuleId = 'virtual:astro-inference/options';
  const resolvedId = '\0' + virtualModuleId;

  return {
    name: 'vite-plugin-astro-inference-options',
    resolveId(id: string) {
      if (id === virtualModuleId) return resolvedId;
    },
    load(id: string) {
      if (id === resolvedId) {
        return `export const options = ${JSON.stringify(options)};`;
      }
    },
  };
}
