import type { MiddlewareHandler } from 'astro';
import { htmlToMarkdown } from './utils/markdown-renderer.js';
import { isExcluded, normalizeSuffix } from './utils/url-utils.js';
import { getPageEntries } from './utils/content-extractor.js';
import { buildLlmsFullTxt, type LlmsFullPage } from './utils/llms-full.js';

const FETCH_TIMEOUT_MS = 10_000;

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

async function fetchPageHtml(origin: string, pagePath: string): Promise<string | null> {
  // Try trailing-slash variant first, then without — covers all trailingSlash configs
  const candidates =
    pagePath === '/'
      ? [`${origin}/`]
      : [`${origin}${pagePath}/`, `${origin}${pagePath}`];

  for (const pageUrl of candidates) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    try {
      const res = await fetch(pageUrl, {
        signal: controller.signal,
        headers: { 'X-Astro-Inference': '1', Accept: 'text/html' },
      });
      if (res.ok) {
        return await res.text();
      }
    } catch {
      // try next candidate
    } finally {
      clearTimeout(timeout);
    }
  }

  return null;
}

export const onRequest: MiddlewareHandler = async (context, next) => {
  const pathname = new URL(context.request.url).pathname;
  const origin = new URL(context.request.url).origin;
  const baseUrl = context.site?.toString().replace(/\/$/, '') ?? origin;
  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;
  const exclude: string[] = options.exclude ?? [];

  const llmsFullTxtPath = normalizeSuffix(options.llmsFullTxtPath ?? '/llms-full.txt');
  if (pathname.replace(/^\//, '') === llmsFullTxtPath) {
    const entries = await getPageEntries(baseUrl, exclude, options.collections);

    const pages: LlmsFullPage[] = [];
    for (const entry of entries) {
      const pageHtml = await fetchPageHtml(origin, entry.url);
      if (pageHtml === null) continue;
      pages.push({ url: `${baseUrl}${entry.url}`, markdown: htmlToMarkdown(pageHtml) });
    }

    const footerText = options.customFooter ?? `Generated by astro-inference | ${baseUrl}/llms.txt`;
    const footer = options.attribution !== false ? footerText : '';

    return new Response(buildLlmsFullTxt(siteName, pages, footer), {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-store',
      },
    });
  }

  const suffix = normalizeSuffix(options.machineSuffix ?? 'machine.txt');

  if (!pathname.endsWith(`/${suffix}`)) {
    return next();
  }

  // Strip /machine.txt to get the original page path
  const pagePath = pathname.slice(0, -(suffix.length + 1)) || '/';

  if (isExcluded(pagePath, exclude)) {
    return next();
  }

  const pageHtml = await fetchPageHtml(origin, pagePath);
  if (pageHtml === null) return next();

  const markdown = htmlToMarkdown(pageHtml);

  const header = [
    `# ${siteName}`,
    `> Source: ${baseUrl}${pagePath}`,
    `> Machine-readable version - ${new Date().toISOString().split('T')[0]}`,
    '',
    '---',
    '',
  ].join('\n');

  const footerText = options.customFooter ?? `Generated by astro-inference | ${baseUrl}/llms.txt`;
  const footer = options.attribution !== false ? `\n---\n${footerText}` : '';

  return new Response(header + markdown + footer, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // No caching in dev — middleware only runs in dev mode
      'Cache-Control': 'no-store',
    },
  });
};
