import type { MiddlewareHandler } from 'astro';
import { htmlToMarkdown } from './utils/markdown-renderer.js';

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

export const onRequest: MiddlewareHandler = async (context, next) => {
  const pathname = new URL(context.request.url).pathname;
  const suffix = options.machineSuffix ?? 'machine.txt';

  if (!pathname.endsWith(`/${suffix}`)) {
    return next();
  }

  const exclude: string[] = options.exclude ?? [];
  // Strip /machine.txt to get the original page path
  const pagePath = pathname.slice(0, -(suffix.length + 1)) || '/';

  if (isExcluded(pagePath, exclude)) {
    return next();
  }

  const origin = new URL(context.request.url).origin;
  const baseUrl = context.site?.toString().replace(/\/$/, '') ?? origin;

  // Fetch the real page — try with trailing slash first (trailingSlash: 'always')
  const pageUrl = `${origin}${pagePath === '/' ? '/' : pagePath + '/'}`;

  let pageHtml: string;
  try {
    const res = await fetch(pageUrl, {
      headers: { 'X-Astro-Inference': '1', Accept: 'text/html' },
    });
    if (!res.ok) return next();
    pageHtml = await res.text();
  } catch {
    return next();
  }

  const markdown = htmlToMarkdown(pageHtml);
  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;
  const machineSuffix = suffix;

  const header = [
    `# ${siteName}`,
    `> Source: ${baseUrl}${pagePath}`,
    `> Machine-readable version - ${new Date().toISOString().split('T')[0]}`,
    '',
    '---',
    '',
  ].join('\n');

  const footer = [
    '',
    '---',
    `Generated by astro-inference | ${baseUrl}/llms.txt`,
  ].join('\n');

  return new Response(header + markdown + footer, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      'Cache-Control': 'public, max-age=3600',
    },
  });
};

function isExcluded(url: string, patterns: string[]): boolean {
  return patterns.some((pattern) => {
    if (pattern.endsWith('/*')) return url.startsWith(pattern.slice(0, -2));
    return url === pattern;
  });
}
