import type { MiddlewareHandler } from 'astro';
import { htmlToMarkdown } from './utils/markdown-renderer.js';
import { isExcluded, normalizeSuffix } from './utils/url-utils.js';

// @ts-ignore - virtual module resolved by Vite plugin at runtime
import { options } from 'virtual:astro-inference/options';

export const onRequest: MiddlewareHandler = async (context, next) => {
  const pathname = new URL(context.request.url).pathname;
  const suffix = normalizeSuffix(options.machineSuffix ?? 'machine.txt');

  if (!pathname.endsWith(`/${suffix}`)) {
    return next();
  }

  const exclude: string[] = options.exclude ?? [];
  // Strip /machine.txt to get the original page path
  const pagePath = pathname.slice(0, -(suffix.length + 1)) || '/';

  if (isExcluded(pagePath, exclude)) {
    return next();
  }

  const origin = new URL(context.request.url).origin;
  const baseUrl = context.site?.toString().replace(/\/$/, '') ?? origin;

  // Try trailing-slash variant first, then without — covers all trailingSlash configs
  const candidates =
    pagePath === '/'
      ? [`${origin}/`]
      : [`${origin}${pagePath}/`, `${origin}${pagePath}`];

  let pageHtml: string | null = null;
  for (const pageUrl of candidates) {
    try {
      const res = await fetch(pageUrl, {
        headers: { 'X-Astro-Inference': '1', Accept: 'text/html' },
      });
      if (res.ok) {
        pageHtml = await res.text();
        break;
      }
    } catch {
      // try next candidate
    }
  }

  if (pageHtml === null) return next();

  const markdown = htmlToMarkdown(pageHtml);
  const siteName = options.siteName ?? new URL(baseUrl || 'http://localhost').hostname;

  const header = [
    `# ${siteName}`,
    `> Source: ${baseUrl}${pagePath}`,
    `> Machine-readable version - ${new Date().toISOString().split('T')[0]}`,
    '',
    '---',
    '',
  ].join('\n');

  const footer =
    options.attribution !== false
      ? `\n---\nGenerated by astro-inference | ${baseUrl}/llms.txt`
      : '';

  return new Response(header + markdown + footer, {
    headers: {
      'Content-Type': 'text/plain; charset=utf-8',
      // No caching in dev — middleware only runs in dev mode
      'Cache-Control': 'no-store',
    },
  });
};
