export interface AstroInferenceOptions {
  /** Site name - used as the # heading in llms.txt */
  siteName?: string;
  /** One-line description of the site */
  siteDescription?: string;
  /**
   * URL paths to exclude from indexing.
   * Supports exact strings and glob-style wildcards (e.g. "/admin/*").
   */
  exclude?: string[];
  /**
   * Content collection names to include in llms.txt.
   * Only the listed collections will be queried — prevents warnings for non-existent collections.
   * Default: auto-tries a set of common names.
   */
  collections?: string[];
  /** Path where llms.txt is served. Default: "/llms.txt" */
  llmsTxtPath?: string;
  /** Suffix appended to each page route for the machine version.
   *  Default: "machine.txt"
   *  Example: /about/machine.txt
   */
  machineSuffix?: string;
  /**
   * Include "Generated by astro-inference" footer in llms.txt and machine.txt output.
   * Default: true
   */
  attribution?: boolean;
}

/** A single page entry used when building llms.txt */
export interface PageEntry {
  url: string;
  title: string;
  description?: string;
  collection?: string;
}
